name: Generate Live JSON

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC (5 AM GMT+3)
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-live-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp rapidfuzz

    - name: Run live_gen.py
      id: generate-json
      run: |
        python live_gen.py > output.json
        echo "JSON generated successfully"
        echo "json_output=$(cat output.json)" >> $GITHUB_OUTPUT

    - name: Encode JSON with custom base32
      id: encode-json
      run: |
        python -c "
        import json
        from pathlib import Path
        
        # Custom encoder (matches the JavaScript implementation)
        _CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef'
        
        def custom_encode(input_string):
            '''Encode string using custom base32 encoding (matches JS implementation)'''
            input_bytes = input_string.encode('utf-8')
            output = []
            bit_buffer = 0
            bit_count = 0
            
            for byte in input_bytes:
                bit_buffer = (bit_buffer << 8) | byte
                bit_count += 8
                
                while bit_count >= 5:
                    bit_count -= 5
                    value = (bit_buffer >> bit_count) & 0x1F
                    output.append(_CHARSET[value])
                    bit_buffer &= (1 << bit_count) - 1
            
            if bit_count > 0:
                bit_buffer <<= (5 - bit_count)
                value = bit_buffer & 0x1F
                output.append(_CHARSET[value])
                output.append('=')
            
            return ''.join(output)
        
        # Read the generated JSON
        with open('output.json', 'r') as f:
            json_data = f.read()
        
        # Validate it's valid JSON
        try:
            json.loads(json_data)
            encoded_data = custom_encode(json_data)
            
            # Create public directory if it doesn't exist
            Path('public').mkdir(exist_ok=True)
            
            # Write encoded data to public/live.json
            with open('public/live.json', 'w') as f:
                f.write(encoded_data)
            
            print('✅ JSON successfully encoded and saved to public/live.json')
            
        except json.JSONDecodeError as e:
            print(f'❌ Error: Invalid JSON generated: {e}')
            exit(1)
        "

    - name: Verify encoded file
      run: |
        echo "Encoded file contents:"
        head -c 100 public/live.json
        echo -e "\n\nFile size: $(wc -c < public/live.json) bytes"

    - name: Deploy to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true

    - name: Upload encoded JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: live-json
        path: public/live.json
